'on':
  github:
    branches:
      only: main
jobs:
  GetModel:
    resources:
      instance-type: P5000
    outputs:
      nudeModel:
        type: volume
    uses: script@v1
    with:
      script: |-
        wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1X4hautXixoVqBo5bq6QXwTc6r4UIBf_q' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1X4hautXixoVqBo5bq6QXwTc6r4UIBf_q" -O modelNudenet.tar.xz && rm -rf /tmp/cookies.txt
        tar xf modelNudenet.tar.xz
        cp -R model /outputs/nudeModel
      image: paperspace/gradient-base:tf29-pt112-py39-2022-06-29

  NudeTest:
    resources:
      instance-type: P5000
    needs:
      - GetModel
    inputs:
      nudeModel: GetModel.outputs.nudeModel
    uses: script@v1
    with:
      script: |-
        git clone https://github.com/dataforgoodfr/bechdelai.git
        cd bechdelai
        git checkout feature/pierre/objectification
        cd objectification
        ls /inputs/nudeModel/model/
        pip install -r requirements.txt
        python3 image_analyser.py
        
      image: paperspace/gradient-base:tf29-pt112-py39-2022-06-29